// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCewSHDF6WJCqPDjvaYVkdyb42EoECODq0',
    appId: '1:62760420733:web:8d8ebf871e7add5f947814',
    messagingSenderId: '62760420733',
    projectId: 'smart-clean-admin',
    authDomain: 'smart-clean-admin.firebaseapp.com',
    databaseURL: 'https://smart-clean-admin-default-rtdb.firebaseio.com',
    storageBucket: 'smart-clean-admin.firebasestorage.app',
    measurementId: 'G-Q36KBEPS7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG3yC21y_vkcfmu8rbUUpajrE79UU60eI',
    appId: '1:62760420733:android:c2423726a5bbf601947814',
    messagingSenderId: '62760420733',
    projectId: 'smart-clean-admin',
    databaseURL: 'https://smart-clean-admin-default-rtdb.firebaseio.com',
    storageBucket: 'smart-clean-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoLRpRzXdK0DX2fGa7R0vu39ApesR5iu8',
    appId: '1:62760420733:ios:1be5c8fc613d7417947814',
    messagingSenderId: '62760420733',
    projectId: 'smart-clean-admin',
    databaseURL: 'https://smart-clean-admin-default-rtdb.firebaseio.com',
    storageBucket: 'smart-clean-admin.firebasestorage.app',
    androidClientId: '62760420733-a3rbm30jocl7p75ks4mbb763d77c5ln3.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoLRpRzXdK0DX2fGa7R0vu39ApesR5iu8',
    appId: '1:62760420733:ios:1be5c8fc613d7417947814',
    messagingSenderId: '62760420733',
    projectId: 'smart-clean-admin',
    databaseURL: 'https://smart-clean-admin-default-rtdb.firebaseio.com',
    storageBucket: 'smart-clean-admin.firebasestorage.app',
    androidClientId: '62760420733-a3rbm30jocl7p75ks4mbb763d77c5ln3.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCewSHDF6WJCqPDjvaYVkdyb42EoECODq0',
    appId: '1:62760420733:web:cb4d5d4f17b1e3a1947814',
    messagingSenderId: '62760420733',
    projectId: 'smart-clean-admin',
    authDomain: 'smart-clean-admin.firebaseapp.com',
    databaseURL: 'https://smart-clean-admin-default-rtdb.firebaseio.com',
    storageBucket: 'smart-clean-admin.firebasestorage.app',
    measurementId: 'G-7WPVK0E2ZB',
  );
}
